### ISSUE TITLE
Help with this Cucumber Scenario??

### ISSUE THREAD

**Issue by DThomas221** [cucumber/cucumber-java-skeleton#54]
Hi, I'm a newbie who's been trying for hours to get cucumber scenario but I keep getting an error is my Scenario?

**Step 1**
Feature: Final Bill Calculation
  @ScenarioOutlineExample
  Scenario Outline: Customer Bill Amount Calculation
    Given I have a Customer
    And user enters intial bill amount as <IntitialBillAmount>
    And Sales Tax Rate is <TaxRate> Percent
    Then final bill amount calculated is <CalculatedBillAmount>

    Examples: 
      | IntitialBillAmount | TaxRate | CalculatedBillAmount |
      |                100 |      10 |                  110 |
      |                200 |       8 |                  216 |
      |                100 |    1.55 |               101.55 |

Step 2 

package stepdefinitions;

import static org.junit.Assert.assertTrue;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import linkedinlearning.cucumbercourse.BillCalculationHelper;

public class ScenarioOutlineSteps {

	int InitalBillAmount;
	double TaxRate;
	
	@Given("I have a Customer")
	public void i_have_a_Customer() {
		
	}

	@Given("user enters intial bill amount as {int}")
	public void user_enters_intial_bill_amount_as(Integer initialBillAmount) {
	    this.InitalBillAmount = initialBillAmount;
	    System.out.println("InitialBillAmount: " + initialBillAmount);
	}

	@Given("Sales Tax Rate is {int} Percent")
	public void sales_Tax_Rate_is_Percent(Integer taxRate) {
	    // Write code here that turns the phrase above into concrete actions
	   this.TaxRate = taxRate;
	   System.out.println("Tax Rate: " + taxRate);
	}

	@Then("final bill amount calculated is {int}")
	public void final_bill_amount_calculate_is(Integer expectedValue) {
		double SystemCalcValue = 
				  BillCalculationHelper.CalculateBillForCustomer(this.InitalBillAmount, this.TaxRate);
		  System.out.println("Expected Value: " + expectedValue);
		  System.out.println("Calculated Value: " + SystemCalcValue);
		  assertTrue(expectedValue == SystemCalcValue);

	}

	@Given("Sales Tax Rate is {double} Percent")
	public void sales_Tax_Rate_is_Percent(Double taxRate) {
	    this.TaxRate = taxRate;
	    System.out.println("Tax Rate: " + taxRate);
	}
	

	
	
	private void invokeWebPage(Double expectedValue) {
		System.setProperty("webdriver.chrome.driver", "C:\\ChromeDriver\\chromedriver.exe");
		
		ChromeDriver driver = new ChromeDriver();
		
		driver.get("http://localhost:8080/BasicWebsite/Index.jsp");
		
		WebElement BillAmountTextBox = driver.findElement(By.id("billamount"));
		
		WebElement TaxRateTextBox = driver.findElement(By.id("taxrate"));
		
		WebElement Button = driver.findElement(By.id("mybutton"));
		
		BillAmountTextBox.sendKeys(Integer.toString(InitalBillAmount));
		
		TaxRateTextBox.sendKeys(Double.toString(TaxRate));
		
		Button.click();
		
		WebElement Header1Element = driver.findElementByXPath("//h1");
		
		System.out.println(Header1Element.getText());
		
		boolean Matched = Header1Element.getText().contains("Final Bill Amount is: $" + expectedValue.toString());
		
		System.out.println(Matched);
		
	
	}
	
	@Then("final bill amount calculated is {double}")
	public void final_bill_amount_calculate_is(Double expectedValue) {
	  double SystemCalcValue = 
			  BillCalculationHelper.CalculateBillForCustomer(this.InitalBillAmount, this.TaxRate);
	  System.out.println("Expected Value: " + expectedValue);
	  System.out.println("Calculated Value: " + SystemCalcValue);
	  assertTrue(expectedValue == SystemCalcValue);	
	  invokeWebPage(expectedValue);
	
	}
}

Step 3 

package testrunners;

import org.junit.runner.RunWith;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;

@RunWith(Cucumber.class)
@CucumberOptions(
		features= {"src/test/java/linkedinlearning/cucumbercourse/features"},
		glue = {"stepdefinitions"},
		plugin= {"pretty",
				"html:target/SystemTestReports/html",
				"json:target/SystemTestReports/json/report.json",
				"junit:target/SystemTestReports/junit/report.xml"},
				tags = "@ScenarioOutlineExample",
				dryRun = false,
				monochrome = true
		)
public class MenuManagementTest {

}

And I  keep  getting this answer:

@ScenarioOutlineExample
Scenario Outline: Customer Bill Amount Calculation # src/test/java/linkedinlearning/cucumbercourse/features/ScenarioOutlineExample.feature:12
  Given I have a Customer                          # stepdefinitions.ScenarioOutlineSteps.i_have_a_Customer()
InitialBillAmount: 100
  And user enters intial bill amount as 100        # stepdefinitions.ScenarioOutlineSteps.user_enters_intial_bill_amount_as(java.lang.Integer)
  And Sales Tax Rate is 10 Percent                 # null
      io.cucumber.core.runner.AmbiguousStepDefinitionsException: "Sales Tax Rate is 10 Percent" matches more than one step definition:
  "Sales Tax Rate is {double} Percent" in stepdefinitions.ScenarioOutlineSteps.sales_Tax_Rate_is_Percent(java.lang.Double)
  "Sales Tax Rate is {int} Percent" in stepdefinitions.ScenarioOutlineSteps.sales_Tax_Rate_is_Percent(java.lang.Integer)
	at io.cucumber.core.runner.CachingGlue.findStepDefinitionMatch(CachingGlue.java:373)
	at io.cucumber.core.runner.CachingGlue.stepDefinitionMatch(CachingGlue.java:341)
	at io.cucumber.core.runner.Runner.matchStepToStepDefinition(Runner.java:146)
	at io.cucumber.core.runner.Runner.createTestStepsForPickleSteps(Runner.java:126)
	at io.cucumber.core.runner.Runner.createTestCaseForPickle(Runner.java:109)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:70)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:151)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:135)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:199)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:90)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:234)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

  Then final bill amount calculate is 110          # null

@ScenarioOutlineExample
Scenario Outline: Customer Bill Amount Calculation # src/test/java/linkedinlearning/cucumbercourse/features/ScenarioOutlineExample.feature:13
  Given I have a Customer                          # stepdefinitions.ScenarioOutlineSteps.i_have_a_Customer()
InitialBillAmount: 200
  And user enters intial bill amount as 200        # stepdefinitions.ScenarioOutlineSteps.user_enters_intial_bill_amount_as(java.lang.Integer)
  And Sales Tax Rate is 8 Percent                  # null
      io.cucumber.core.runner.AmbiguousStepDefinitionsException: "Sales Tax Rate is 8 Percent" matches more than one step definition:
  "Sales Tax Rate is {double} Percent" in stepdefinitions.ScenarioOutlineSteps.sales_Tax_Rate_is_Percent(java.lang.Double)
  "Sales Tax Rate is {int} Percent" in stepdefinitions.ScenarioOutlineSteps.sales_Tax_Rate_is_Percent(java.lang.Integer)
	at io.cucumber.core.runner.CachingGlue.findStepDefinitionMatch(CachingGlue.java:373)
	at io.cucumber.core.runner.CachingGlue.stepDefinitionMatch(CachingGlue.java:341)
	at io.cucumber.core.runner.Runner.matchStepToStepDefinition(Runner.java:146)
	at io.cucumber.core.runner.Runner.createTestStepsForPickleSteps(Runner.java:126)
	at io.cucumber.core.runner.Runner.createTestCaseForPickle(Runner.java:109)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:70)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:151)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:135)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:199)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:90)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:234)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

  Then final bill amount calculate is 216          # null

@ScenarioOutlineExample
Scenario Outline: Customer Bill Amount Calculation # src/test/java/linkedinlearning/cucumbercourse/features/ScenarioOutlineExample.feature:14
  Given I have a Customer                          # stepdefinitions.ScenarioOutlineSteps.i_have_a_Customer()
InitialBillAmount: 100
  And user enters intial bill amount as 100        # stepdefinitions.ScenarioOutlineSteps.user_enters_intial_bill_amount_as(java.lang.Integer)
Tax Rate: 1.55
  And Sales Tax Rate is 1.55 Percent               # stepdefinitions.ScenarioOutlineSteps.sales_Tax_Rate_is_Percent(java.lang.Double)
  Then final bill amount calculate is 101.55       # null

Also 

![cumcuber](https://user-images.githubusercontent.com/74933140/100019209-437b3800-2da3-11eb-8b3e-5ccfcaf0637f.JPG)

![cumcuber2](https://user-images.githubusercontent.com/74933140/100019241-51c95400-2da3-11eb-91d9-513e852396a5.JPG)

Please help me tell me what I did wrong??

**Comment by aslakhellesoy** [comment]
So you have a step:

```gherkin
And Sales Tax Rate is 10 Percent
```

which has the following step text: `Sales Tax Rate is 10 Percent`

You have defined two step definitions:

```java
@Given("Sales Tax Rate is {int} Percent")
public void sales_Tax_Rate_is_Percent(Integer taxRate) {
    // Write code here that turns the phrase above into concrete actions
   this.TaxRate = taxRate;
   System.out.println("Tax Rate: " + taxRate);
}

@Given("Sales Tax Rate is {double} Percent")
public void sales_Tax_Rate_is_Percent(Double taxRate) {
    this.TaxRate = taxRate;
    System.out.println("Tax Rate: " + taxRate);
}
```

Their expressions both match the step text, so Cucumber cannot determine which one you want to run. You have to remove the ambiguity. It's a bit like defining the same method twice. It's a kind of compile error.

I suggest you remove the first one and try again.

**Comment by DThomas221** [comment]
Hey aslakhellesoy,

I also add a few more information

**Comment by aslakhellesoy** [comment]
I assume you are happy with this answer. If not, please reopen.

**Comment by DThomas221** [comment]
Reopen

**Comment by DThomas221** [comment]
No, how do I reopen this question

**Comment by DThomas221** [comment]
What about the multiple markers at this line??

**Comment by aslakhellesoy** [comment]
Multiple markers at what line??

Please use the [support](https://cucumber.io/tools/cucumber-open/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by DThomas221** [comment]
![100019209-437b3800-2da3-11eb-8b3e-5ccfcaf0637f](https://user-images.githubusercontent.com/74933140/100143416-ea6edb00-2e5a-11eb-966d-82e85c1c6a02.jpg)
![100019241-51c95400-2da3-11eb-91d9-513e852396a5](https://user-images.githubusercontent.com/74933140/100143420-eba00800-2e5a-11eb-9064-81beda99a08e.jpg)


int InitalBillAmount;
double TaxRate;

@Given("I have a Customer")
public void i_have_a_Customer() {
	
}

@Given("user enters intial bill amount as {int}")
public void user_enters_intial_bill_amount_as(Integer initialBillAmount) {
    this.InitalBillAmount = initialBillAmount;
    System.out.println("InitialBillAmount: " + initialBillAmount);
}

@Given("Sales Tax Rate is {int} Percent")
public void sales_Tax_Rate_is_Percent(Integer taxRate) {
    // Write code here that turns the phrase above into concrete actions
   this.TaxRate = taxRate;
   System.out.println("Tax Rate: " + taxRate);
}

@Then("final bill amount calculated is {int}")
public void final_bill_amount_calculate_is(Integer expectedValue) {
	double SystemCalcValue = 
			  BillCalculationHelper.CalculateBillForCustomer(this.InitalBillAmount, this.TaxRate);
	  System.out.println("Expected Value: " + expectedValue);
	  System.out.println("Calculated Value: " + SystemCalcValue);
	  assertTrue(expectedValue == SystemCalcValue);

}

@Given("Sales Tax Rate is {double} Percent")
public void sales_Tax_Rate_is_Percent(Double taxRate) {
    this.TaxRate = taxRate;
    System.out.println("Tax Rate: " + taxRate);
}




private void invokeWebPage(Double expectedValue) {
	System.setProperty("webdriver.chrome.driver", "C:\\ChromeDriver\\chromedriver.exe");
	
	ChromeDriver driver = new ChromeDriver();
	
	driver.get("http://localhost:8080/BasicWebsite/Index.jsp");
	
	WebElement BillAmountTextBox = driver.findElement(By.id("billamount"));
	
	WebElement TaxRateTextBox = driver.findElement(By.id("taxrate"));
	
	WebElement Button = driver.findElement(By.id("mybutton"));
	
	BillAmountTextBox.sendKeys(Integer.toString(InitalBillAmount));
	
	TaxRateTextBox.sendKeys(Double.toString(TaxRate));
	
	Button.click();
	
	WebElement Header1Element = driver.findElementByXPath("//h1");
	
	System.out.println(Header1Element.getText());
	
	boolean Matched = Header1Element.getText().contains("Final Bill Amount is: $" + expectedValue.toString());
	
	System.out.println(Matched);
	

}

@Then("final bill amount calculated is {double}")
public void final_bill_amount_calculate_is(Double expectedValue) {
  double SystemCalcValue = 
		  BillCalculationHelper.CalculateBillForCustomer(this.InitalBillAmount, this.TaxRate);
  System.out.println("Expected Value: " + expectedValue);
  System.out.println("Calculated Value: " + SystemCalcValue);
  assertTrue(expectedValue == SystemCalcValue);	
  invokeWebPage(expectedValue);

}
