### ISSUE TITLE
Help Needed: Cucumber Test with Spring Boot from Executable Jar

### ISSUE THREAD

**Issue by cgohil** [cucumber/cucumber-java-skeleton#65]
I have maven project with Spring Boot and Cucumber with JUnit5. Test works fine with maven and from intellij.

But when I create executable test jar it fails to find the context configuration.

Error Message:

Exception in thread "main" io.cucumber.core.exception.CucumberException: io.cucumber.core.backend.CucumberBackendException: Please annotate a glue class with some context configuration.

For example:
```
   @CucumberContextConfiguration
   @SpringBootTest(classes = TestConfig.class)
   public class CucumberSpringConfiguration { }
Or:

   @CucumberContextConfiguration
   @ContextConfiguration( ... )
   public class CucumberSpringConfiguration { }
    at io.cucumber.core.runtime.CucumberExecutionContext.getException(CucumberExecutionContext.java:82)
    at io.cucumber.core.runtime.Runtime.run(Runtime.java:103)
    at io.cucumber.core.cli.Main.run(Main.java:92)
    at com.test.cucumber.runner.CucumberTestRunner.main(CucumberTestRunner.java:25)
Caused by: io.cucumber.core.backend.CucumberBackendException: Please annotate a glue class with some context configuration.

For example:

   @CucumberContextConfiguration
   @SpringBootTest(classes = TestConfig.class)
   public class CucumberSpringConfiguration { }
Or:

   @CucumberContextConfiguration
   @ContextConfiguration( ... )
   public class CucumberSpringConfiguration { }
    at io.cucumber.spring.SpringFactory.start(SpringFactory.java:129)
    at io.cucumber.core.runner.Runner.buildBackendWorlds(Runner.java:99)
    at io.cucumber.core.runner.Runner.runPickle(Runner.java:67)
    at io.cucumber.core.runtime.Runtime.lambda$execute$5(Runtime.java:110)
    at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
    at io.cucumber.core.runtime.Runtime.lambda$execute$6(Runtime.java:110)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:233)
    at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
    at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:86)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
    at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at io.cucumber.core.runtime.Runtime.run(Runtime.java:87)

```

Code Sample: https://github.com/cgohil/spring-cucumber-test-executable

To create executable jar:
```
mvn clean install
```

To run test cases from test-jar:
```
java -jar target/spring-cucumber-test-executable-1.0.0-SNAPSHOT-test-jar-with-dependencies.jar classpath:com/test/cucumber/FunctionalTest.feature
```

**Comment by mpkorstanje** [comment]
Questions like this are better suited for Stackoverflow.

That said I'm guessing you didn't configure the assembly plugin to merge the service descriptors from different artefacts. Both cucumber-java and cucumber-spring define a few. 

Check `metaInf-services` here:

https://maven.apache.org/plugins/maven-assembly-plugin/examples/single/using-container-descriptor-handlers.html
